
# middleware.py
class ContentSecurityPolicyMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)


        # allowed_domains = [
        #     "https://kpyx.co",
        #     "https://www.kpyx.co",
        #     "https://185.100.87.158:8000",
        #     "https://kpyx.io",
        #     "https://www.kpyx.io",
        #     "https://www.krmp.io",
        #     "https://krmp.io",
        #     "https://2krk.site",
        #     "https://portfolio-gzbf.onrender.com",
        #     "https://krm.gg",
        #     "https://knm.st",
        #     "https://2kkm.co",
        #     "https://2kk.site",
        #     "https://2kramp.site",
        #     "https://2kk.ac",
        #     "https://2kkn.ac",
        #     "https://2kkm.st",
        #     "https://torkrn.cc",
        #     "https://torkrn.co",
        #     "https://2krk.in",
        #     "https://2krm.st",
        #     "https://2knmp.cc",
        #     "https://kkn.st",
        #     "https://2kkn.st",
        #     "https://2kkn.top",
        #     "https://tkm.ac",
        #     "https://tkm.cx",
        #     "https://tkm.gg",
        #     "https://2kkm.mx",
        #     "https://2kn.io",
        #     "https://dkm.gg",
        #     "https://2kk.to",
        #     "https://2kk.is",
        #     "https://2kk.ai",
        #     "https://2kk.cx",
        #     "https://2kk.mx",
        #     "https://2kk.sh",
        #     "https://2kk.so",
        #     "https://knmp.cc",
        #     "https://knmp.st",
        #     "https://zerkalo-kra.cc",
        #     "https://zerkalokrn.cc",
        #     "https://dkm.ac",
        #     "https://kr2.ai",
        #     "https://kr2.me",
        #     "https://kr2.is",
        #     "https://km2.is",
        #     "https://4kra.co",
        #     "https://2kn.is",
        #     "https://4kr.co",
        #     "https://t.me",
        #     "https://web.telegram.org",
        #     "https://cyberrpg.gg",
        #     "https://cyberika.gg",
        #     "https://knmp.io",
        #     "https://krn.is",
        #     "https://install.kkrn.co",
        #     "https://cybercity.gg",
        #     "https://km2.ac",
        #     "https://cybertown.gg",
        #     "https://3km.ac",
        #     "https://3km.so",
        #     "https://3km.gg",
        #     "https://kn1.ac",
        #     "http://1kn.ac",
        #     "https://1kn.ac",
        #     "https://kn2.cx",
        #     "https://ddna.top",
        #     "https://kr2.nl",
        #     "https://kuzbass.pro",
        #     "https://mafiacity.gg",
        #     "https://kuzbass.gg",
        #     "https://2kra.tv",
        #     "https://3km.me",
        #     "https://1kn.ac",
        #     "https://1kdm.cc",
        #     "https://1kdm.me",
        #     "https://kn3.me",
        #     "https://3km.nl",
        #     "https://kr-adresa.cc"
        #
        #
        # ]
        allowed_domains = [
            "https://izwup9lqklxynpqndg3d.net",
            "https://4p8ox2caq4cs6tpudhrm.gg",
            "https://rpsu59dbldj3krxr2fs0.org",
            "https://pn3fa5iu35r1chnsie6t.co",
            "https://bjl7xb2umxeshmv8aqft.gg",
            "https://pwmlls2r3j81xr7izglc.info",
            "https://xatar5uo4va2nlt3206o.io",
            "https://kpyx.co",
            "https://ttjrmulobj8fxxw1li7n.io",
            "https://p3ciwy34ajrr9vuq05sf.org",
            "https://6589vb6qoswn0inunuzc.com",
            "https://xhfkobkklplec94ckz4c.com",
            "https://0iz7uw5dpoei945nob6v.org",
            "https://g3vog7jvl6do9v99t11s.info",
            "https://t5k8iz3nbul5ilah05ij.co",
            "https://c58yr9ba43vppx1dyrh7.net",
            "https://www.kpyx.co",
            "https://6589vb6qoswn0inunuzc.com",
            "https://xhfkobkklplec94ckz4c.com",
            "https://185.100.87.158:8000",
            "https://kpyx.io",
            "https://c58yr9ba43vppx1dyrh7.net",
            "https://lk76neaxdjkplxs00jrx.info",
            "https://hlishw36ailsc8vgdl4i.co",
            "https://ueul6sz2n1ci5mupn98e.info",
            "https://jrdfko9a7txpzads0fel.info",
            "https://www.kpyx.io",
            "https://al4b2ye1j6bo40v4k1k2.net",
            "https://dy44b0wd5w50f7cpfdqw.net",
            "https://zylrlioyo8znnxw0jjr1.info",
            "https://m0scbuhxvc384unk4kmm.gg",
            "https://www.krmp.io",
            "https://krmp.io",
            "https://2krk.site",
            "https://f71lu6rjh6mebz1uuo1q.com",
            "https://ustklsssfqoitolu4rc8.co",
            "https://cx1gwsfrlsutly3e6e6b.org",
            "https://ckj8hcs2s2jy89fnlp67.com",
            "https://y04nvgbaan91fcs7y43d.com",
            "https://ee4skxn2376ml4z4milk.io",
            "https://ik6ertr168yxyac8bd81.net",
            "https://portfolio-gzbf.onrender.com",
            "https://krm.gg",
            "https://knm.st",
            "https://2kkm.co",
            "https://2kk.site",
            "https://2kramp.site",
            "https://2kk.ac",
            "https://2kkn.ac",
            "https://2kkm.st",
            "https://torkrn.cc",
            "https://torkrn.co",
            "https://2krk.in",
            "https://2krm.st",
            "https://2knmp.cc",
            "https://kkn.st",
            "https://2kkn.st",
            "https://2kkn.top",
            "https://tkm.ac",
            "https://tkm.cx",
            "https://tkm.gg",
            "https://2kkm.mx",
            "https://2kn.io",
            "https://dkm.gg",
            "https://2kk.to",
            "https://2kk.is",
            "https://2kk.ai",
            "https://2kk.cx",
            "https://2kk.mx",
            "https://2kk.sh",
            "https://2kk.so",
            "https://knmp.cc",
            "https://knmp.st",
            "https://zerkalo-kra.cc",
            "https://zerkalokrn.cc",
            "https://dkm.ac",
            "https://kr2.ai",
            "https://kr2.me",
            "https://kr2.is",
            "https://km2.is",
            "https://4kra.co",
            "https://2kn.is",
            "https://4kr.co",
            "https://t.me",
            "https://web.telegram.org",
            "https://cyberrpg.gg",
            "https://cyberika.gg",
            "https://knmp.io",
            "https://krn.is",
            "https://install.kkrn.co",
            "https://cybercity.gg",
            "https://km2.ac",
            "https://cybertown.gg",
            "https://3km.ac",
            "https://3km.so",
            "https://3km.gg",
            "https://kn1.ac",
            "http://1kn.ac",
            "https://1kn.ac",
            "https://kn2.cx",
            "https://ddna.top",
            "https://kr2.nl",
            "https://kuzbass.pro",
            "https://mafiacity.gg",
            "https://kuzbass.gg",
            "https://2kra.tv",
            "https://3km.me",
            "https://1kn.ac",
            "https://1kdm.cc",
            "https://1kdm.me",
            "https://kn3.me",
            "https://3km.nl",
            "https://kr-adresa.cc"

        ]

        frame_ancestors = ' '.join(allowed_domains)


        response['Content-Security-Policy'] = f"frame-ancestors {frame_ancestors}"

        return response
