# Generated by Django 5.0.6 on 2024-07-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
